### ISSUE TITLE
Enable remote access to Prometheus and Grafana

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#13]
Setup and document the method for remotely accessing the could monitoring services.

Ideally these services will be visible via port forwarding or a proxy. An alternative solution could be ssh-tunneling.

**Comment by GregBlow** [comment]
https://www.wiki.ed.ac.uk/pages/viewpage.action?pageId=545089905

For reference, there is still a task (external to Somerville) to upgrade ACF to routed network that will make this possible over internet without port tunnelling. However, as this issue is now nearly years old, I am closing as the requested mechanism is in place and satisfactory if suboptimal.
