### ISSUE TITLE
Failed mgmt ethernet port on sv-ssd-0-7

### ISSUE THREAD

**Issue by astrodb** [lsst-uk/somerville-operations#165]
Investigate and fix the failed 10Gbps network port on sv-ssd-0-7. If it is the ethernet device itself, schedule a callout with HPE.

**Comment by GregBlow** [comment]
There is unlikely to be a way to access the OS that sv-ssd-0-7 is running, on healthy nodes the user accounts I know of are locked, so they're only accessible by ssh:
```
[stack@sv-ssd-0-6 ~]$ sudo passwd -S stack
stack LK 2023-12-08 0 99999 7 -1 (Password locked.)
[stack@sv-ssd-0-6 ~]$ sudo passwd -S root
root LK 1969-12-31 0 99999 7 -1 (Password locked.)
```
Which blocks using the iLO remote console. In the iLO the network interface presents identically to the same network interface on a healthy node. I have tried the node on a known healthy cable and switch port, and tried a healthy node 

We can likely boot to single user mode to get diagnostic information, but this will entail an outage that requires us to either:

1) rebalance the cluster across the remaining 6 ssd nodes (presuming capacity), or
2) down the node and suffer the loss of resiliency

Suggested order of events:

1) Raise case, will likely be asked for AHS logs (which show nothing wrong) or output from installed OS (can't because no access)
2) Arrange to boot into single user mode, will entail an outage on the order of an hour that will entail some reshuffling or some risk, depending on occupancy.
3) Get output from:
 - [ ] `ip l`
 - [ ] `lspci | grep Ethernet`
 - (specify others)
4) return ceph node to service 
5) Arrange maintenance
6) withdraw node from service (again)
7) get node repaired
8) return to service

steps 4 & 6 dependent on risk evaluation. All subsequent steps dependent on output of step 3 commands.

**Comment by astrodb** [comment]
I copied the ssh key for the Stack user to sv-ssd-0-1, then used it from there to login to sv-ssd-0-7 over ther high speed network.

Results of initial OS checks:

`[stack@sv-ssd-0-7 ~]$ ip l

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

2: ens1f0np0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 88:e9:a4:0e:30:d4 brd ff:ff:ff:ff:ff:ff
    altname enp135s0f0np0

3: ens1f1np1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 88:e9:a4:0e:30:d4 brd ff:ff:ff:ff:ff:ff permaddr 88:e9:a4:0e:30:d5
    altname enp135s0f1np1

4: ens10f0np0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether bc:97:e1:a7:b1:9c brd ff:ff:ff:ff:ff:ff
    altname enp198s0f0np0

5: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 88:e9:a4:0e:30:d4 brd ff:ff:ff:ff:ff:ff

6: bond0.3304@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 88:e9:a4:0e:30:d4 brd ff:ff:ff:ff:ff:ff

7: bond0.3305@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 88:e9:a4:0e:30:d4 brd ff:ff:ff:ff:ff:ff

8: ens10f1np1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether bc:97:e1:a7:b1:9d brd ff:ff:ff:ff:ff:ff
    altname enp198s0f1np1

[stack@sv-ssd-0-7 ~]$ lspci | grep Ethernet

87:00.0 Ethernet controller: Mellanox Technologies MT28908 Family [ConnectX-6]

87:00.1 Ethernet controller: Mellanox Technologies MT28908 Family [ConnectX-6]

c6:00.0 Ethernet controller: Broadcom Inc. and subsidiaries BCM57416 NetXtreme-E Dual-Media 10G RDMA Ethernet Controller (rev 01)

c6:00.1 Ethernet controller: Broadcom Inc. and subsidiaries BCM57416 NetXtreme-E Dual-Media 10G RDMA Ethernet Controller (rev 01)
`

**Comment by astrodb** [comment]
Further looking into the connection with nmcli:

`[stack@sv-ssd-0-7 ~]$ nmcli connection show

NAME        UUID                                  TYPE      DEVICE
lo          62d34b75-6dd4-4338-a688-1b1b150460e3  loopback  lo
bond0.3304  cff2bbfa-a371-3376-b703-6f2352893d25  vlan      bond0.3304
bond0.3305  c1ea2994-67d3-35eb-a437-4a9801d88f62  vlan      bond0.3305
ens10f0np0  ab587e3d-a57c-38af-a2ec-9206d16f0b6e  ethernet  ens10f0np0
bond0       75ac1a13-dbce-36e4-8ecb-c6ed6fce5322  bond      bond0
ens1f0np0   eb493ea9-d520-3245-84a6-3ec875342216  ethernet  ens1f0np0
ens1f1np1   73660a25-b271-3657-bf8d-c5cc7f90e88d  ethernet  ens1f1np1

[stack@sv-ssd-0-7 ~]$ nmcli device status

DEVICE      TYPE      STATE                   CONNECTION
lo          loopback  connected (externally)  lo
ens10f0np0  ethernet  connected               ens10f0np0
bond0.3304  vlan      connected               bond0.3304
bond0.3305  vlan      connected               bond0.3305
bond0       bond      connected               bond0
ens1f0np0   ethernet  connected               ens1f0np0
ens1f1np1   ethernet  connected               ens1f1np1
ens10f1np1  ethernet  disconnected            --
`

**Comment by astrodb** [comment]
Can you try connecting the cable again? OS thinks the connection is down, so can't test a lot else at the moment from there.

**Comment by GregBlow** [comment]
Both ports on the network card look to be detected by the network card, but dead. Submitting case to HPE.
