### ISSUE TITLE
Redeploy supermicro hypervisors with SSDs for Gaia

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#74]
- [ ] Remove sv-sm-0-[0-3] from service
- [ ] Perform installation of SSDs into each node
- [ ] Readd sv-sm-0-[0-3] into service
- [ ] Apply to new availability zone

**Comment by GregBlow** [comment]
@astrodb Do we want the new availability zone (when this comes around) to be marked as Gaia specific (i.e. just call it 'gaia-sm') or more generic ('supermicro' will likely stay distinctive, if not descriptive)?

**Comment by astrodb** [comment]
Keep it generic.

**Comment by Zarquan** [comment]
> Keep it generic.

I agree. Not least because the Gaia team (myself and Stelios) are still learning and we may end up changing our requirements. At some stage we may end up using different hardware for the Gaia project and the `supermicro` machines are assigned to a different project.

**Comment by Zarquan** [comment]
If we do need to tag anything to link it to our Gaia project, it might be better to use `gaia-dmp` rather than just `gaia`.

Our project, the _Gaia DataMiningPlatform (Gaia-DMp)_, is but a small part of the overall Gaia data processing effort. Somerville may end up hosting other data processing tasks for the Gaia telescope, and we don't want to block them by taking too generic a name.

**Comment by GregBlow** [comment]
as QServ work has become a higher priority I am bumping the SSD replacement for at least the remainder of the week.
