### ISSUE TITLE
Object storage API timeouts

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#93]
Sometimes the Object storage service just times out. Appears to happen with both S3 and Swift.

 This is a trivial test that uploads one small object at a time and times how long it takes:
```
(s3test) ubuntu@gftest2:~/s3test$ python3 upload.py 
0 0.0340
1 0.0735
2 0.0190
3 0.0168
4 0.0212
5 0.0205
6 61.6514
7 0.0192
8 0.0735
9 0.0705
10 0.0126
11 0.0138
12 62.0552
13 0.0141
14 0.0128
15 0.0124
16 0.0723
17 0.0742
18 62.0583
19 0.0135
20 0.0122
21 0.0125
22 0.0130
23 0.0129
24 61.2402
25 0.0153
26 0.0125
27 0.0116
28 0.0128
29 0.0129
30 61.3146
31 0.0688
32 0.0120
33 0.0242
34 0.0125
35 0.0111
36 61.7825
37 0.0122
38 0.2429
39 0.0719
40 0.0122
41 0.0135
42 61.7005
43 0.0132
44 0.0113
45 0.0140
46 0.0734
47 0.0796
48 61.5335
49 0.0136
50 0.0128
51 0.0127
52 0.0121
53 0.0180
54 61.8846
55 0.0135
56 0.0131
57 0.0113
58 0.0116
59 0.0164
60 61.1643
61 0.1770
62 0.0130
63 0.0126
64 0.0144
65 0.0118
```

**Comment by astrodb** [comment]
This problem was caused by a faulty rgw daemon on sv-hdd-12-1. Stopping the daemon resulted in no more timeout errors. The daemon has since been deleted and redeployed. Please confirm whether or not this issue is resolved.

note: the troubleshooting for this issue (restarting a subset of the rgw daemons) appears to have triggered a bug in Ceph which resulted in deep scrubs failing. See: https://github.com/lsst-uk/somerville-operations/issues/97

**Comment by gpfrancis** [comment]
No, I'm afraid the problem is back.
```
(s3test) ubuntu@gftest2:~/s3test$ python3 upload.py 
0.1016
0.1577
0.0656
0.0689
0.0136
0.0113
61.3793
0.0164
0.0161
0.1000
0.0256
0.0544
61.8280
```

**Comment by astrodb** [comment]
OK, moving back to "In Progress". 

The issue is occuring on the same daemon/machine as before. I'll liase with StackHPC to see what we can do.

**Comment by astrodb** [comment]
Tests done, and all is working after the upgrade.
